baseURL = "https://yourhome786.netlify.app/"
languageCode = "en-us"
title = "Your Home"
publishDir = "public"

[params]
  name = "Your Home"
  email = "wwwmuhammadawais72@gmail.com"
  phone = "+92 300 1234567"
  address = "Lahore, Pakistan"

[mediaTypes]
  [mediaTypes."text/netlify"]
    suffix = "netlify"

[outputFormats]
  [outputFormats.NETLIFY]
    mediaType = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "NETLIFY"]
  page = ["HTML"]
  section = ["HTML"]